name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install VS Code extension dependencies
      working-directory: support/vscode-vegen
      run: npm ci

    - name: Build VS Code extension
      working-directory: support/vscode-vegen
      run: npx @vscode/vsce package

    - name: Build release binary
      run: cargo build --release --verbose

    - name: Package binary
      run: |
        cd target/release
        tar -czf vegen-linux-x64.tar.gz vegen

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          target/release/vegen-linux-x64.tar.gz
          support/vscode-vegen/*.vsix
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
